sherlockode_sylius_acb_admin_page:
    resource: |
        alias: sherlockode_sylius_acb.page
        section: admin
        templates: '@SyliusAdmin\\Crud'
        except: ['show']
        redirect: update
        grid: sherlockode_sylius_acb_admin_page
        vars:
            index:
                icon: 'sticky note'
            all:
                templates:
                    form: "@SherlockodeSyliusAdvancedContentPlugin/admin/Page/_form.html.twig"
    type: sylius.resource

sherlockode_sylius_acb_admin_content:
    resource: |
        alias: sherlockode_sylius_acb.content
        section: admin
        templates: '@SyliusAdmin\\Crud'
        except: ['show']
        redirect: update
        grid: sherlockode_sylius_acb_admin_content
        vars:
            index:
                icon: 'sticky note outline'
            all:
                templates:
                    form: "@SherlockodeSyliusAdvancedContentPlugin/admin/Content/_form.html.twig"
    type: sylius.resource

sherlockode_sylius_acb_admin_scope_init:
    path: "/scope/init"
    defaults:
        _controller: sherlockode_sylius_acb.controller.scope::updateScopesAction

sherlockode_sylius_acb_admin_page_preview:
    path: "/preview/{pageIdentifier}"
    defaults:
        _controller: sherlockode_sylius_acb.controller.preview::previewAction
