services:

    sherlockode_sylius_acb_menu_listener:
        class: Sherlockode\SyliusAdvancedContentPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
    
    sherlockode_advanced_content.user_provider:
        class: Sherlockode\SyliusAdvancedContentPlugin\User\AdminUserProvider
        arguments: 
            - '@translator'
            - '@security.token_storage'
            - '@sylius.repository.admin_user'
    sherlockode_advanced_content.scope_handler:
        class: Sherlockode\SyliusAdvancedContentPlugin\Scope\ChannelLocaleScopeHandler
