services:

    sherlockode_sylius_acb_menu_listener:
        class: Sherlockode\SyliusAdvancedContentPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
    
    sherlockode_advanced_content.user_provider:
        class: Sherlockode\SyliusAdvancedContentPlugin\User\AdminUserProvider
        arguments: 
            - '@translator'
            - '@security.token_storage'
            - '@sylius.repository.admin_user'
    sherlockode_advanced_content.scope_handler:
        class: Sherlockode\SyliusAdvancedContentPlugin\Scope\ChannelLocaleScopeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sherlockode_advanced_content.configuration_manager'
            - '@sylius.context.channel'
            - '@sylius.context.locale'

    sherlockode_sylius_acb.scope_initializer:
        class: Sherlockode\SyliusAdvancedContentPlugin\Scope\ScopeInitializer
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sherlockode_advanced_content.configuration_manager'
    sherlockode_sylius_acb.scope_init_command:
        class: Sherlockode\SyliusAdvancedContentPlugin\Command\ScopeInitCommand
        arguments:
            - '@sherlockode_advanced_content.configuration_manager'
            - '@translator'
            - '@sherlockode_sylius_acb.scope_initializer'
        tags:
            - { name: console.command }
    sherlockode_sylius_acb.controller.scope:
        class: Sherlockode\SyliusAdvancedContentPlugin\Controller\ScopeController
        public: true
        arguments:
            - '@sherlockode_advanced_content.configuration_manager'
            - '@sherlockode_sylius_acb.scope_initializer'
            - '@translator'
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: container.service_subscriber }
    sherlockode_sylius_acb.scope_extension:
        class: Sherlockode\SyliusAdvancedContentPlugin\Twig\Extension\ScopeExtension
        arguments:
            - '@sherlockode_advanced_content.configuration_manager'
            - '@sherlockode_sylius_acb.scope_initializer'
        tags:
            - { name: twig.extension }
    
