sylius_resource:
    resources:
        sherlockode_sylius_acb.page:
            driver: doctrine/orm
            classes:
                model: Sherlockode\SyliusAdvancedContentPlugin\Entity\Page
                form: Sherlockode\AdvancedContentBundle\Form\Type\PageType
                repository: Sherlockode\SyliusAdvancedContentPlugin\Repository\PageRepository
        sherlockode_sylius_acb.content:
            driver: doctrine/orm
            classes:
                model: Sherlockode\SyliusAdvancedContentPlugin\Entity\Content
                form: Sherlockode\AdvancedContentBundle\Form\Type\ContentType
