sylius_resource:
    resources:
        sherlockode_sylius_acb.page:
            driver: doctrine/orm
            classes:
                model: Sherlockode\AdvancedContentBundle\Entity\Page
                form: Sherlockode\AdvancedContentBundle\Form\Type\PageType
        sherlockode_sylius_acb.content:
            driver: doctrine/orm
            classes:
                model: Sherlockode\AdvancedContentBundle\Entity\Content
                form: Sherlockode\AdvancedContentBundle\Form\Type\ContentType
